spring.application.name=vault_nest
spring.datasource.url=jdbc:postgresql://localhost:7432/vaultnestdb
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true